WebUI/Models/BooksListViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class BooksListViewModel
    {
        public IEnumerable<Book> Books { get; set; }
        public PagingInfo PagingInfo { get; set; } 
        public string CurrentGenre { get; set; }
    }
}

WebUI/Models/CartIndexViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }    //Общее количество книг
        public int ItemsPerPage { get; set; }  //Кол-во книг на странице
        public int CurrentPage { get; set; }   //Номер текущей страницы
        public int TotalPages                  //Общее кол-во страниц
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

WebUI/Controllers/AdminController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class AdminController : Controller
    {
        IBookRepository repository;
        public AdminController(IBookRepository repo)
        {
            repository = repo;
        }
        public ViewResult Index()
        {
            return View(repository.Books);
        }
        public ViewResult Edit(int bookId)
        {
            Book book = repository.Books.FirstOrDefault(b=>b.BookId == bookId);
            return View(book);
        }

        [HttpPost]
        public ActionResult Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                repository.SaveBook(book);
                TempData["message"] = string.Format("Изменения информации о книге \"{0}\" сохранены", book.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(book);
            }
        }
    }
}

WebUI/Controllers/BooksController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class BooksController : Controller
    {
        private IBookRepository repository;
        public int pageSize = 4;
        public BooksController(IBookRepository repo)
        {
            repository = repo;
        }
        public ViewResult List(string genre,int page =1)
        {
            BooksListViewModel model = new BooksListViewModel
            {
                Books = repository.Books
                .Where(b => genre == null || b.Genre == genre)
                .OrderBy(book => book.BookId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = genre == null ? 
                        repository.Books.Count() : 
                        repository.Books.Where(book => book.Genre == genre).Count()
                },
                CurrentGenre = genre
            };
            return View(model);
        }
    }
}

WebUI/Controllers/CartController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
        private IBookRepository repository;
        private IOrderProcessor orderProcessor;
        public CartController(IBookRepository repo,IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }

        public ViewResult Index(Cart cart,string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
        public RedirectToRouteResult AddToCart(Cart cart,int bookId, string returnUrl)
        {
            Book book = repository.Books
                .FirstOrDefault(b => b.BookId == bookId);

            if (book!= null)
            {
                cart.AddItem(book,1);
            }
            return RedirectToAction("Index",new { returnUrl});
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int bookId, string returnUrl)
        {
            Book book = repository.Books
                .FirstOrDefault(b => b.BookId == bookId);

            if (book != null)
            {
                cart.RemoveLine(book);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, корзина пуста");
            }
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(new ShippingDetails());
            }
        }
    }
}

WebUI/Controllers/NavController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        private IBookRepository repository;
        public NavController( IBookRepository repo)
        {
            repository = repo;
        }
        public PartialViewResult Menu(string genre = null  )
        {
            ViewBag.SelectedGenre = genre;
            IEnumerable<string> genres = repository.Books
                .Select(book => book.Genre)
                .Distinct()
                .OrderBy(x => x);
            return PartialView("FlexMenu",genres);
        }
    }
}

WebUI/Views/Admin/Edit.cshtml
@model Domain.Entities.Book

@{
    ViewBag.Title = "Админ панель: редактирование товара";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h3>Редактирование книги "@Model.Name"</h3>
    </div>
    @using (Html.BeginForm())
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.BookId)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                if (property.PropertyName != "BookId")
                {
                    <div class="form-group">
                        <label>@(property.DisplayName ?? property.PropertyName)</label>
                        @if (property.PropertyName == "Description")
                        {
                            @Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 })
                        }
                        else
                        {
                            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                        }
                        @Html.ValidationMessage(property.PropertyName)
                    </div>
                }
            }
        </div>
        <div class="panel-footer">
            <input type="submit" value="Сохранить" class="btn btn-primary" />
            @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

WebUI/Views/Admin/Index.cshtml
@model IEnumerable<Domain.Entities.Book>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        Список книг
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">
                    @Html.DisplayNameFor(model => model.BookId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Author)
                </th>
                <th class="text-right">
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th class="text-center">
                    Действия
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">
                        @item.BookId
                    </td>
                    <td>
                        @Html.ActionLink(item.Name, "Edit", new { item.BookId })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Author)
                    </td>
                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td class="text-center">
                       @using (Html.BeginForm("Delete","Admin"))
                       {
                           @Html.Hidden("BookId",item.BookId)
                           <input type="submit" class="btn btn-default btn-xs" value="Удалить" />
                       }

                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Добавить", "Create", null, new { @class = "btn btn-default" })
    </div>
</div>

WebUI/Views/Books/List.cshtml
@using WebUI.Models
@model BooksListViewModel

@{
    ViewBag.Title = "Книги";
}

@foreach (var book in Model.Books)
{
   @Html.Partial("_BookSummary",book)
}
<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, genre = Model.CurrentGenre }))
</div>

WebUI/Views/Cart/Checkout.cshtml
@model Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "BookStore: форма заказа";
}

<h2>Оформить заказ</h2>
<p>Пожалуйста, введите Ваши контактные данные.</p>

@using (Html.BeginForm())
{
    @Html.ValidationSummary();
    <h3>Данные</h3>
    <div class="form-group">
        <label>Ваше имя:</label>
        @Html.TextBoxFor(x=>x.Name,new { @class = "form-control"})
    </div>

    <h3>Адрес доставки</h3>
   foreach (var property in ViewData.ModelMetadata.Properties)
   {
       if (property.PropertyName != "Name" && property.PropertyName != "GiftWrap")
       {
           <div class="form-group">
               <label>
                   @(property.DisplayName ?? property.PropertyName)
               </label>
               @Html.TextBox(property.PropertyName, null, new { @class="form-control" })
           </div>
       }
   }
    
    <h3>Опции</h3>
    <div class="form-group">
        <label>
           @Html.EditorFor(x=>x.GiftWrap)
           Использовать подарочную упаковку? 
        </label>
    </div>
    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Обработать заказ" />
    </div>
} 

WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Заказ обработан";
}

<h2>Спасибо!</h2>
<p>Спасибо за выбор нашего магазина. В ближайшее время заказ будет отправлен.</p>

WebUI/Views/Cart/Index.cshtml
@model WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "BookStore - Ваша корзина";
}

<h2>@ViewBag.Title</h2>
<table id="cartTable" class="table">
    <thead>
        <tr>
            <th>Количество</th>
            <th>Наименование</th>
            <th class="text-right">Цена</th>
            <th class="text-right">Сумма</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Book.Name - @line.Book.Author</td>
                <td class="text-right">@line.Book.Price.ToString("# руб")</td>
                <td class="text-right">@((line.Quantity * line.Book.Price).ToString("# руб"))</td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("BookId",line.Book.BookId)
                        @Html.HiddenFor(x=>x.ReturnUrl)
                        <input class="btn btn-sm btn-warning" type="submit" value="Удалить" /> 
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Итого:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("# руб")
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Продолжить покупки</a> 
    @Html.ActionLink("Оформить заказ","Checkout",null,new { @class="btn btn-primary"})
</div>

WebUI/Views/Cart/Summary.cshtml
@model Domain.Entities.Cart

<div class="navbar-right hidden-xs">
    @Html.ActionLink("Заказать", "Index", "Cart",
             new { returnUrl = Request.Url.PathAndQuery },
             new { @class = "btn btn-default navbar-btn" })
</div>

<div class="navbar-right visible-xs">
    <a href=@Url.Action("Index","Cart",new { returnUrl =Request.Url.PathAndQuery }) class="btn btn-default navbar-btn">
        <span class="glyphicon gliphicon-shopping-cart"></span>
    </a>
</div>
<div class="navbar-text navbar-right">
    <b class="hidden-xs">Ваша корзина</b>
    @Model.Lines.Sum(x => x.Quantity) книг,
    @Model.ComputeTotalValue().ToString("# руб")
</div>

WebUI/Views/Nav/FlexMenu.Mobile.cshtml
@model IEnumerable<string>

<div data-role="navbar">
    <ul>
        @foreach (var link in Model)
            {
            <li>
                @Html.RouteLink(link, new
               {
                   controller = "Books",
                   action = "List",
                   genre = link,
                   page = 1
               },
       new
       {
           data_transition = "fade",
           @class = (link == ViewBag.SelectedGenre ? "ui-btn-active" : null)
       })
            </li>
        }
    </ul>
</div>

WebUI/Views/Nav/FlexMenu.cshtml
@model IEnumerable<string>

@{ 
    bool horizontal = (bool)(ViewContext.RouteData.Values["HorizontalNav"] ?? false);
    string wrapperClasses = horizontal ? "btn-group btn-group-sm btn-group-justified" : null;
}
<div class="@wrapperClasses">
    @Html.ActionLink("Домой", "List", "Books", null,
    new
    {
        @class = horizontal ? "btn btn-default btn-sm" :
        "btn btn-block btn-default btn-lg"
    })

    @foreach (var link in Model)
    {
        @Html.RouteLink(link, new
   {
       controller = "Books",
       action = "List",
       genre = link,
       page = 1
   },
       new
       {
           @class = (horizontal ? "btn btn-default btn -sm":
           "btn btn-block btn-default btn-lg")
           + (link == ViewBag.SelectedGenre ? "btn -primary" : "")
       })
    }
</div>

WebUI/Views/Shared/_AdminLayout.cshtml
@{ 
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"]!=null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

WebUI/Views/Shared/_BookSummary.Mobile.cshtml
@model Domain.Entities.Book
<div data-role="collapsible" data-collapsed="false" data-content-theme="c">
    <h2>@Model.Name</h2>
    <h3>@Model.Author</h3>
    <div>
        <div>
            @Model.Description
        </div>
        <div>
            <strong>@Model.Price.ToString("# руб")</strong>
        </div>
        <div>
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                @Html.HiddenFor(x => x.BookId)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="В корзину" />
            }
        </div>
    </div>
</div>

WebUI/Views/Shared/_BookSummary.cshtml
@model Domain.Entities.Book
<div class="well">
    <div class="row">
        <div class="col-xs-9">
            <h3>
                <strong>@Model.Name</strong>
            </h3>
            <h4>
                <strong>@Model.Author</strong>
            </h4>
        </div>
        <div class="col-xs-3">
            <h3>
                <strong id="price" class="pull-right label label-primary">
                    @Model.Price.ToString("# руб")
                </strong>
            </h3>
            @using (Html.BeginForm("AddToCart","Cart"))
            {
                <div class="pull-right">
                    @Html.HiddenFor(x=>x.BookId)
                    @Html.Hidden("returnUrl",Request.Url.PathAndQuery)
                    <input type="submit" class="btn btn-success" value="В корзину"/>
                </div>
            }

        </div>
    </div>
    <span class="lead">
        @Model.Description
    </span>
</div>

WebUI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
          href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div data-role="page" id="page1">
        <div data-theme="a" data-role="header" data-position="fixed">
            <h3>BookStore</h3>
            @Html.Action("Menu", "Nav")
        </div>
        <div data-role="content">
            <ul data-role="listview" data-dividertheme="b" data-inset="false">
                <li>@RenderBody()</li>
            </ul>
        </div>
    </div>
</body>
</html>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">
            <span class="hidden-xs">BookStore - книжный магазин</span>
            <div class="visible-xs">Book</div>
            <div class="visible-xs">Store</div>
        </a>
        @Html.Action("Summary", "Cart")
    </div>

    <div class="visible-xs">
        @Html.Action("Menu","Nav", new { horizontalNav = true })
    </div>

    <div class="row panel">
        <div id="genres" class="col-sm-3 hidden-xs">
            @Html.Action("Menu", "Nav");
        </div>
        <div class="col-xs-12 col-sm-8">
            @RenderBody()
        </div>
    </div>


</body>
</html>